name:                bad-words-diff
version:             0.1.0.0
github:              "googleson78/bad-words-diff"
license:             BSD3
author:              "Georgi Lyubenov"
maintainer:          "godzbanebane@gmail.com"
copyright:           "2018 Georgi Lyubenov"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: ex nihilo

dependencies:
- base >= 4.7 && < 5
- process
- diff-parse
- text

library:
  source-dirs: src

executables:
  bad-words-diff-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bad-words-diff

tests:
  bad-words-diff-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bad-words-diff
